---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.4.3
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: [alertmanager.prosto.dev]
            annotations:
              item.homer.rajsingh.info/name: "Alertmanager"
              item.homer.rajsingh.info/subtitle: "Monitoring Alerts Management"
              item.homer.rajsingh.info/logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/alertmanager.webp"
              service.homer.rajsingh.info/name: "Observability"
              service.homer.rajsingh.info/icon: "fas fa-eye"
        grafana:
          admin:
            existingSecret: grafana-admin
            userKey: admin-user
            passwordKey: admin-password
          persistence:
            enabled: true
            size: 10Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: [grafana.prosto.dev]
            annotations:
              item.homer.rajsingh.info/name: "Grafana"
              item.homer.rajsingh.info/subtitle: "Monitoring Dashboards"
              item.homer.rajsingh.info/logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/grafana.webp"
              service.homer.rajsingh.info/name: "Observability"
              service.homer.rajsingh.info/icon: "fas fa-eye"
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: [prometheus.prosto.dev]
            annotations:
              item.homer.rajsingh.info/name: "Prometheus"
              item.homer.rajsingh.info/subtitle: "Metrics TSDB"
              item.homer.rajsingh.info/logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/prometheus.webp"
              service.homer.rajsingh.info/name: "Observability"
              service.homer.rajsingh.info/icon: "fas fa-eye"
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
