---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: blocky
  namespace: blocky
  labels:
    app: blocky

spec:
  replicas: 3
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: blocky
      containers:
        - name: blocky
          image: ghcr.io/0xerr0r/blocky:v0.29.0
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 4000
              name: http
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: blocky-config
