---
apiVersion: v1
kind: Service

metadata:
  name: blocky
  namespace: blocky
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.88.50

spec:
  type: LoadBalancer
  selector:
    app: blocky
  ports:
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
