---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: prosto-dev-wildcard
  namespace: ingress

spec:
  secretName: prosto-dev-wildcard-tls
  issuerRef:
    kind: ClusterIssuer
    name: prosto-dev
  commonName: "*.prosto.dev"
  dnsNames:
    - "*.prosto.dev"
    - "prosto.dev"  # Good practice to include the root domain too
