---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: prosto-dev

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: prosto-dev+legalaze94@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-prosto-dev-dns-token
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: prosto-dev-wildcard
  namespace: ingress

spec:
  secretName: prosto-dev-wildcard-tls
  issuerRef:
    kind: ClusterIssuer
    name: prosto-dev
  commonName: "*.prosto.dev"
  dnsNames:
    - "*.prosto.dev"
    - "prosto.dev"
