{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}

spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.storeName }}
    kind: ClusterSecretStore
  dataFrom:
      - extract:
          key: {{ .bitwardenKey }}
{{- end }}
