---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    app.kubernetes.io/part-of: external-secrets

spec:
  groups:
    - name: external-secrets
      rules:
        - alert: ExternalSecretSyncError
          expr: |
            externalsecret_status_condition{condition="Ready",status="False"} == 1
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: 'ExternalSecret {{ printf "{{ $labels.name }}" }}/{{ printf "{{ $labels.namespace }}" }} sync has failed'
