---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-9"

spec:
  project: default
  source:
    repoURL: oci://ghcr.io/traefik/helm/traefik
    chart: traefik
    targetRevision: 40.0.0-ea.1
    helm:
      releaseName: traefik
      valuesObject:
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          listeners:
            web:
              namespacePolicy:
                from: All
            websecure:
              port: 8443
              protocol: HTTPS
              namespacePolicy:
                from: All
              certificateRefs:
                - name: prosto-dev-wildcard-tls
                  group: ""
                  kind: Secret
                  namespace: ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
