---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: cnpg-atuin
  namespace: atuin

spec:
  instances: 3
  storage:
    size: 5Gi
  walStorage:
    size: 2Gi
  postgresql:
    parameters:
      wal_keep_size: "128MB"
      max_wal_size: "512MB"
  bootstrap:
    initdb:
      database: atuin
      owner: atuin

