---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: cnpg-atuin
  namespace: atuin

spec:
  instances: 3
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      database: atuin
      owner: atuin

