---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.io/charts/
      chart: cloudnative-pg
      targetRevision: 0.28.0
      helm:
        releaseName: cnpg-operator
        valuesObject:
          monitoring:
            podMonitorEnabled: true
            grafanaDashboard:
              create: true
    - repoURL: https://github.com/atimofeev/homelab
      targetRevision: HEAD
      path: apps/cnpg-operator
      directory:
        exclude: main.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
