---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey

metadata:
  name: nix-cache
  namespace: garage

spec:
  clusterRef:
    name: garage
  name: "Nix Cache Key"
  secretTemplate:
    name: nix-cache-s3-credentials
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
    endpointKey: S3_ENDPOINT
    regionKey: AWS_REGION
    includeEndpoint: true
    includeRegion: true
  bucketPermissions:
    - bucketRef: nix-cache
      read: true
      write: true
      owner: true
