---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageAdminToken

metadata:
  name: admin-token
  namespace: garage

spec:
  clusterRef:
    name: garage
  name: Full Admin Token
  neverExpires: true
  secretTemplate:
    name: garage-admin-token
    tokenKey: admin-token
    includeEndpoint: true
