---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: media
  namespace: arr-stack
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-media
  resources:
    requests:
      storage: 250Gi
