---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: bento-pdf
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/atimofeev/homelab
    targetRevision: HEAD
    path: apps/bento-pdf
    directory:
      exclude: main.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bento-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
