---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: paperless-django-secret
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: credentials

spec:
  length: 64
  digits: 16
  symbols: 0
  allowRepeat: true
  encoding: base64url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: paperless-django-secret
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: credentials

spec:
  refreshPolicy: CreatedOnce
  target:
    name: paperless-django-secret
    creationPolicy: Orphan
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: paperless-django-secret
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: paperless-admin-password
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: credentials

spec:
  length: 32
  digits: 8
  symbols: 0
  allowRepeat: true
  encoding: base64url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: paperless-admin-secret
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: paperless-ngx
    app.kubernetes.io/component: credentials

spec:
  refreshPolicy: CreatedOnce
  target:
    name: paperless-admin-secret
    creationPolicy: Orphan
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: paperless-admin-password
